CREATE TABLE users (
id SERIAL PRIMARY KEY,
name TEXT DEFAULT NULL
);

CREATE TABLE tweets (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) NOT NULL,
content TEXT DEFAULT NULL,
imgurl TEXT DEFAULT NULL
);